title: "Yung's /dev/null"
email: "yung7.ho@gmail.com" 
description: >-
  AI Undergrad @ Soochow Univ. 
  Arch Linux, Neovim, and Deep Learning.
baseurl: "" 
url: "https://hyong7.github.io"
twitter_username: 
github_username: hyong7

style: dark

header_pages:
  - about.markdown
  - archive.md

plugins:
  - jekyll-seo-tag
